markdown: redcarpet
name: Data-Driven Government Toolkit
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author: Data Community DC membership & collaborators
  name: Data Community DC
  url: https://datacommunitydc.org

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/dc2-logo.png
logoalt: Data Community DC logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
- text: Add a new page
  url: add-a-new-page/
  internal: true
  children:
  - text: Make a child page
    url: make-a-child-page/
    internal: true
- text: Add images
  url: add-images/
  internal: true
- text: Update the config file
  url: update-the-config-file/
  internal: true
  children:
  - text: Understanding the `baseurl:` property
    url: understanding-baseurl/
    internal: true
- text: GitHub setup
  url: github-setup/
  internal: true
- text: Post your guide
  url: post-your-guide/
  internal: true
- text: Advanced features
  url: advanced-features/
  internal: true

repos:
- name: Data-Driven Government Toolkit
  description: Main repository
  url: https://github.com/nihonjinrxs/data-driven-government-toolkit
- name: 18F Guides Template
  description: Upstream repository
  url: https://github.com/18F/guides-template

back_link:
  url: "https://datacommunitydc.org"
  text: More Data Community DC content

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
